acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.ulogin, name="login"),
    path('logout/', views.ulogout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('delete/', views.delete, name="delete"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path('chpass/', views.chpass, name="chpass"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('join/', include('join.urls')),
    path('board/', include('board.urls')),
    path('todo/', include('todo.urls')),
    path('info/', include('info.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

join/urls.py
from django.urls import path
from . import views

app_name = "join"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('detail/<jpk>', views.detail, name="detail"),
    path('delete/<jpk>', views.delete, name="delete"),
    path('create/', views.create, name="create"),
    path('jlikey/<jpk>', views.jlikey, name="jlikey"),
    path('unjlikey/<jpk>', views.unjlikey, name="unjlikey")
]

join/models.py
from django.db import models
from acc.models import User
from django.utils import timezone

# Create your models here.
class Join(models.Model):
    jsubject = models.CharField(max_length=100)
    jwriter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="jwriter", default='')
    jcontent = models.TextField()
    jpubdate = models.DateTimeField(default=timezone.now)
    jlikey = models.ManyToManyField(User, blank=True, related_name="jlikey")
    
    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"
    
    def __str__(self):
        return self.jsubject

class jReply(models.Model):
    jboard = models.ForeignKey(Join, on_delete=models.CASCADE)
    jreplyer = models.ForeignKey(User, on_delete=models.CASCADE)
    jcomment = models.TextField()

    def __str__(self):
        return f"{self.jboard}_{self.jreplyer} 님의 댓글"

join/views.py
from django.shortcuts import render, redirect
from .models import Join, jReply
from django.core.paginator import Paginator
from django.contrib import messages

# Create your views here.
def unjlikey(request, jpk):
    j = Join.objects.get(id=jpk)
    j.jlikey.remove(request.user)
    return redirect("join:detail", jpk)

def jlikey(request, jpk):
    j = Join.objects.get(id=jpk)
    j.jlikey.add(request.user)
    return redirect("join:detail", jpk)

def index(request):
    cate = request.GET.get("cate", "")
    kw = request.GET.get("kw", "")
    pg = request.GET.get("page", 1)

    if kw:
        if cate == "sub":
            j = Join.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                j = Join.objects.filter(jwriter=u)
            except:
                pass
        elif cate == "con":
            j = Join.objects.filter(content__contains=kw)
    else:
        j = Join.objects.all()

    pag = Paginator(j, 3)
    obj = pag.get_page(pg)
    context = {
        "jset" : obj,
        "cate" : cate,
        "kw" : kw,
    }
    return render(request, "join/index.html", context)

def detail(request, jpk):

    if request.user.is_anonymous:
        return redirect("acc:login")

    j = Join.objects.get(id=jpk)
    context = {
        "j" : j
    }
    return render(request, 'join/detail.html', context)

def delete(request, jpk):
    j = Join.objects.get(id=jpk)
    if j.jwriter == request.user:
        j.delete()
    else:
        messages.warning(request, "비정상적 접근입니다.")
    return redirect("join:index")

def create(request):
    if request.method == "POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        Join(jsubject=s, jcontent=c, jwriter=request.user).save()
        return redirect("join:index")
    return render(request, "join/create.html")

templates/join/create.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>게시글 생성</b></h1>

    <form method="post">
        {% csrf_token %}
        <input class="form-control mt-5" name="sub" placeholder="INPUT SUBJECT">
        <input class="form-control mt-4 mb-4" value="{{ user }}" disabled>
        <textarea class="form-control" name="con" style="height: 250px;" placeholder="INPUT CONTENT"></textarea>

        <div class="text-end mt-4">
            <button class="btn btn-dark">생성하기</button>
        </div>
    </form>
{% endblock %}

templates/join/detail.html
{% extends 'base.html' %}

{% block con %}
    <h1><b>{{ j.jsubject }}</b></h1>

    <div class="text-end">
        <button type="button" class="btn btn-outline-warning" data-bs-toggle="modal" data-bs-target="#post">
            ✨
        </button>
    </div>

    <div class="row mt-5">
        <div class="col-sm-9">
            <textarea class="form-control" style="height: 250px;" disabled>{{ j.jcontent }}</textarea>
        </div>
        <div class="col-sm-3">
            <img src="{{ j.jwriter.getpic }}" width="100%">
            <div class="text-center mt-3">
                <h4>written by <b>{{ j.jwriter }}</b></h4>
            </div>
            <div class="text-end mt-2">
                {{ j.jpubdate|date:'Y년 m월 d일 / H:i' }}
            </div> 
        </div>
    </div>

    <div class="text-end mt-4">
        <a href="{% url 'join:index' %}" class="btn btn-dark">메인</a>

        {% if user in j.jlikey.all %}
            <a href="{% url 'join:unjlikey' j.id %}" class="btn btn-danger">좋아요취소</a>
        {% else %}
            <a href="{% url 'join:jlikey' j.id %}" class="btn btn-primary">좋아요</a>
        {% endif %}
        
        {% if user == j.jwriter %}
            <a href="#" class="btn btn-secondary">수정</a>
            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                삭제
            </button>
        {% endif %}
        
    </div>

    <!-- 삭제모달창 -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">게시글 삭제 알림창</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">닫기</button>
                    <a href="{% url 'join:delete' j.id %}" type="button" class="btn btn-danger">삭제하기</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/join/index.html
{% extends 'base.html' %}

{% block con %}
    {% load mathfilters %}
    <h1><b>스터디 개설 및 참여</b></h1>
    <br>
    <h5>STUDY MATES 에서 함께할 팀원을 찾으세요 🔍</h5>

    <div class="text-end">
        <a class="btn btn-dark" href="{% url 'join:create' %}">WRITE</a>
    </div>

    <table class="table table-hover mt-4" height="300">
        <thead>
            <tr class="table-dark">
                <th scope="col">NO</th>
                <th scope="col">SUBJECT</th>
                <th scope="col">WRITER</th>
                <th scope="col">SUMMARY</th>
                <th scope="col">LIKEY</th>
            </tr>
        </thead>
        <tbody>
            {% for i in jset %}
                <tr>
                    <th scope="row">{{ jset.start_index|add:forloop.counter0 }}</th>
                    <td><a href="{% url 'join:detail' i.id %}" class="sub">{{ i.jsubject }}</a></td>
                    <td>{{ i.jwriter }}</td>
                    <td>{{ i.jcontent|truncatewords:6 }}</td>
                    <td>{{ i.jlikey.count }}</td>
                </tr>
            {% empty %}
                <tr class="text-center">
                    <th colspan="5"><h4>{% if kw %} 검색결과가 존재하지 않습니다 {% else %} 첫번째 게시글을 작성해주세요 {% endif %}</h4></th>
                </tr>
            {% endfor %}
        
        </tbody>
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if jset.has_previous %}
            <li class="page-item"><a class="page-link" href="{% url 'join:index' %}?page=1&cate={{cate}}&kw={{kw}}">First</a></li>
            <li class="page-item"><a class="page-link" href="{% url 'join:index' %}?page={{ jset.previous_page_number }}&cate={{cate}}&kw={{kw}}">Prev</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">First</a></li>
                <li class="page-item disabled"><a class="page-link">Prev</a></li>
            {% endif %}
    
            {% for i in jset.paginator.page_range %}
                {% if i >= jset.number|sub:3 and jset.number|add:3 >= i %}
                    <li class="page-item {% if i == jset.number %} active {% endif %}"><a class="page-link" href="{% url 'join:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}">{{i}}</a></li>
                {% endif %}
            {% endfor %}
    
            {% if jset.has_next %}
                <li class="page-item"><a class="page-link" href="{% url 'join:index' %}?page={{ jset.next_page_number }}&cate={{cate}}&kw={{kw}}">Next</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'join:index' %}?page={{ jset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}">Last</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link">Next</a></li>
                <li class="page-item disabled"><a class="page-link">Last</a></li>
            {% endif %}
        </ul>
    </nav>

    <form>
        <div class="row">
            <div class="col-sm-2">
                <select class="form-select" name="cate">
                    <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
                    <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
                    <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>
                </select>
            </div>
            <div class="col-sm-8">
                <input type="text" name="kw" value="{{kw}}" class="form-control" placeholder="검색어를 입력해주세요">
            </div>
            <div class="col-sm-1">
                <button class="btn btn-dark" style="width: 100%;">검색</button>
            </div>
            <div class="col-sm-1">
                <a class="btn btn-secondary" href="{% url 'join:index' %}" style="width: 100%;">초기화</a>
            </div>
        </div>
    </form>

    {% for k, v in dic.items %}
        {{ k }} {{ v }} <br>
    {% endfor %}

    <style>
        .sub {
            text-decoration: none;
            color: black;
            font-weight: bold;
        }
        .sub:hover{
            color:brown;
        }
    </style>
{% endblock %}